EXP: "ResNet50FPN_fold0"

DATA:
    FOLD: 0
    IN_CHANS: 3
    CUTMIX: True
    IMG_SIZE: 640

TRAIN:
    EPOCHS: 300
    BATCH_SIZE: 32

OPT:
    WARMUP_EPOCHS: 30
    BASE_LR: 1e-3
    WEIGHT_DECAY: 0.0

MODEL:
    BACKBONE:
        NAME: "swsl_resnet50"
        OUT_FEATURES: ["res2", "res3", "res4", "res5"]
        OUTPUT_STRIDE: 32
    FPN:
        NORM: "BN"
    SEM_SEG_HEAD:
        NUM_CLASSES: 5
        NORM: "BN"

LOSS:
    NAME: "dice"

OPT:
    GD_STEPS: 1